[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "nss", "atk", "cups", "dbus", "glib", "gtk3"]

[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
